### PR TITLE
Delete `printed_parts/archive` folder

### PR DESCRIPTION
**Pull request by DeflateAwning**
Storing deleted files in a folder in a git repo is a bit of an anti-pattern, and goes against the ideas of version control.

This PR removes these presumably-now-obsolete files that are presumably captured in previous releases and are thus no longer needed in an archive folder.

### CODE REVIEW

**Comment by crocsg** [comment]
I agree this is a bit overkill while using versioning system. But i know many BrailleRAP users who are afraid of using git, and still download what they need from the head of master branch. Since there is no disadvantage for advanced users, and some user find it useful  i will preserve archive directory.

**Comment by DeflateAwning** [comment]
Using git properly and leading by example is a good way to help people understand how it's meant to be used. Using it incorrectly won't make people less afraid of it. I doubt anyone is going to try printing those parts without understanding what version they're for (e.g., what version of documentation, what version of side panels, etc.). 

If you want an even easier system than git, let's add the downloads to the documentation/website, with direct links to the GitHub Releases files!

Other benefit: the downloaded files are smaller, and simpler to work with.

**Comment by crocsg** [comment]
OK. So, you started a Pull Request proposing to delete a folder. I explain why i will not, and let the conversation open. So you give us some git lessons. May i remind you that the purpose of this project is not to give git course. This project is about :
- Building something useful together.
- Collaboration in a positive state of mind.
- Talking about accessibility and benefit of IT technologies for it.
- Talking about IT technology for sharing and better living.
- Talking about open licences and their benefits in real life.
- Making functional devices for people who desperately need them.
- Desacralize the complexity of building a digital machine.

And the last and maybe not the least, git never put a bunch of Braille in a children hand, and all beloved contributors of this project have do so. I'm open to discussion about better way to collaborate and welcome any contribution, but i will not ask the BrailleRAP community to become git professional.

**Comment by DeflateAwning** [comment]
Oh trust me, this is far from professional. 

I can't believe that you're proud of using tools badly and declining help to use those tools properly. This is really strange.

**Comment by crocsg** [comment]
Sorry, but you diverge from the topic of this conversation by focusing on git. On the subject of declining help, it seems i've accepted some of your PR, and if i remind well with a "thanks for the contribution" somewhere. On this specific PR, you suggest to delete a folder with 20 files, and it seems i've explained why i will not accept this specific PR. You just react on 3 different posts with your (bad) opinion about the commit log, contributors who are not sufficiently git aware. and suggest to replace an existing documentation by something more git aware. Considering that you came on this project 4 days ago, and that i'm contributing on BrailleRAP since more than  6 years, maybe you should consider that you don't know each details and context of this project. 
Saying that, pretending that it is proudness to take care of need expressed by enduser some time ago is :
- your opinion
- a little bit irrespectful, and maybe more than a little bit.

**Comment by DeflateAwning** [comment]
Sorry if you thought I was being disrespectful; definitely wasn't the intention. When I found this project, I was excited to help contribute, and to make it easier for others to contribute. 

I actually know several people in this same boat, who couldn't figure out how to deal with the project's disjointed structure.

Anyway, I won't be thinking about it anymore, as it's clear that your goals don't align with mine (contributing to a simple, low-barrier open source Braille embosser). Best of luck, but I'm out!

**Pull request closed without merging**
